defaults:
    - agent: diayn_gher

env:  AntEnv



#env: square

# this needs to be specified manually
experiment: test_exp

num_train_steps: 1000000
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 5000

eval_frequency: 10000
num_eval_episodes: 10

device: cuda

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: true


seed: 1


max_replay_buffer_size : ${num_train_steps}


# GHER ARGPARSERS. SETTING THEM UP WITH DEFAULT VALUES:

alg: DIAYN
n_sampled_latents : 5
n_to_take: 1
relabel: true
use_advantages: true
irl: true
plot: true
cache : true
sparse: None
ngradsteps: 100
nexpl: None
horizon: None
tau: 5e-3
lr: None
buffer_size: None
discount : None
gpu : 0
ec2: false
local_docker: false
reward_scale : Null 
insert_time: true
latent_shape_multiplier : 1
latent_to_all_layers: true
n_experiments: -1 
exp_name: None
extra: None
test: true
epochs: 100
save_videos: true
safetyfn: newlog
energyfn: velocity
energyfactor: 1.0
truncate_obs: true 
use_xy: true 
contact_forces: true 
directiontype : 360
# latent_dim: 3



# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}
